// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHk0m1a13XEkjfmmLeG4OqVtDPWPvWWU',
    appId: '1:395614433230:web:fe900772e9f1e17036c59f',
    messagingSenderId: '395614433230',
    projectId: 'powergymapp-62d75',
    authDomain: 'powergymapp-62d75.firebaseapp.com',
    databaseURL: 'https://powergymapp-62d75-default-rtdb.firebaseio.com',
    storageBucket: 'powergymapp-62d75.firebasestorage.app',
    measurementId: 'G-37GVGN9T57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_16FRHtKPjynfdeHnvHyGEvb3omMuqM',
    appId: '1:395614433230:android:128c2aaa5e808b3036c59f',
    messagingSenderId: '395614433230',
    projectId: 'powergymapp-62d75',
    databaseURL: 'https://powergymapp-62d75-default-rtdb.firebaseio.com',
    storageBucket: 'powergymapp-62d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fGmS_YVyJUh9ZViKDGoOu0lsjkHd1aI',
    appId: '1:395614433230:ios:ba670db499910da136c59f',
    messagingSenderId: '395614433230',
    projectId: 'powergymapp-62d75',
    databaseURL: 'https://powergymapp-62d75-default-rtdb.firebaseio.com',
    storageBucket: 'powergymapp-62d75.firebasestorage.app',
    iosBundleId: 'com.example.powerGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1fGmS_YVyJUh9ZViKDGoOu0lsjkHd1aI',
    appId: '1:395614433230:ios:ba670db499910da136c59f',
    messagingSenderId: '395614433230',
    projectId: 'powergymapp-62d75',
    databaseURL: 'https://powergymapp-62d75-default-rtdb.firebaseio.com',
    storageBucket: 'powergymapp-62d75.firebasestorage.app',
    iosBundleId: 'com.example.powerGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYHk0m1a13XEkjfmmLeG4OqVtDPWPvWWU',
    appId: '1:395614433230:web:a390ea150144c5ef36c59f',
    messagingSenderId: '395614433230',
    projectId: 'powergymapp-62d75',
    authDomain: 'powergymapp-62d75.firebaseapp.com',
    databaseURL: 'https://powergymapp-62d75-default-rtdb.firebaseio.com',
    storageBucket: 'powergymapp-62d75.firebasestorage.app',
    measurementId: 'G-M3DPY2LJ4X',
  );
}
